bitebuddy:
  email:
    address: "mail.bitebuddy@gmail.com"
    smtp:
      host: "smtp.gmail.com"
      port: 587
      username: "mail.bitebuddy@gmail.com"
      password: "nuem wfjl fhnz zrvd"
file-paths:
  key-security-folder: "security"
  private-key-filename: "private.pem"
  public-key-filename: "public.pem"
  pictures:
    recipe-folder: "pictures/recipe"
  data:
    folder: "data"
    filename:
      recipe: "Recipes.json"
      ingredient: "Ingredients.json"
      allergen: "Allergenes.json"
      allergen-ingredient: "AllergeneIngredients.json"
      recipe-ingredient: "RecipeIngredients.json"
logging:
  level:
    root: INFO
    at.ac.tuwien.sepr.groupphase.backend.*: TRACE #TODO DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
  charset:
    console: 'utf-8'
    file: 'utf-8'
  file:
    name: ./log/backend.log
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} | %clr(%5p) | %clr(%-35.35logger{35}){yellow} %clr(---){faint} %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSSXXX} r=%X{r} ip=%X{ip} | %5p | [%clr(${PID:- }){magenta}] [%thread] %logger{45}: %msg%n'
    level: r=%X{r} ip=%X{ip} u=%X{u} %5p
  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 100MB

spring:
  datasource:
    url: jdbc:h2:file:./database/db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    # Set this property to true if you want to see the executed queries
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

management:
  server:
    port: 8081
  endpoint:
    shutdown:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - shutdown
          - metrics
          - env
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  shutdown: graceful
